# Generated by Django 6.0 on 2025-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlog', '0002_alter_category_options_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='0', max_length=20),
        ),
    ]
